# NumPy Fundamentals: A Comprehensive Guide

## 1. Environment Setup & Version Check
Initialize NumPy and verify the installed runtime version.

In [1]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.2.6


## 2. Array Creation & Data Types
Demonstrating implicit type coercion in standard Python lists versus NumPy's homogeneous array requirement.

In [2]:
# Python heterogeneous list
py_list = [1, 2, 2.5, "Ahmed"]
print("py_list:", py_list)

# Standard integer array
int_array = np.array([1, 2, 3])
print("int_array:", int_array)

# Coerced string array due to homogeneous type enforcement
str_array = np.array([1, 2, 3, "4"])
print("str_array:", str_array)

py_list: [1, 2, 2.5, 'Ahmed']
int_array: [1 2 3]
str_array: ['1' '2' '3' '4']


### Initializing Arrays from Scratch

In [3]:
# Array of zeros (length 10)
zeros_arr = np.zeros(10)
print("zeros_arr:\n", zeros_arr)

# 3x5 array filled with floating-point ones
ones_arr = np.ones((3, 5))
print("ones_arr:\n", ones_arr)

# 3x5 array filled with a specific constant
full_arr = np.full((3, 5), 3.14)
print("full_arr:\n", full_arr)

# Linear sequence with step size (start, stop, step)
step_arr = np.arange(0, 21, 2)
print("step_arr:\n", step_arr)

# Evenly spaced sequence over a specified interval
linspace_arr = np.linspace(0, 1, 5)
print("linspace_arr:\n", linspace_arr)

# Uniformly distributed random floats between 0 and 1
rand_float_arr = np.random.random((3, 5))
print("rand_float_arr:\n", rand_float_arr)

# Random integers in a given range [0, 6)
rand_int_arr = np.random.randint(0, 6, (3, 5))
print("rand_int_arr:\n", rand_int_arr)

# 3x3 Identity matrix
identity_matrix = np.eye(3)
print("identity_matrix:\n", identity_matrix)

# Uninitialized array with unallocated memory values
empty_arr = np.empty((3, 5))
print("empty_arr:\n", empty_arr)

zeros_arr:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones_arr:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full_arr:
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
step_arr:
 [ 0  2  4  6  8 10 12 14 16 18 20]
linspace_arr:
 [0.   0.25 0.5  0.75 1.  ]
rand_float_arr:
 [[0.5943835  0.27162512 0.35888216 0.60834223 0.92024103]
 [0.45550566 0.85581454 0.74499243 0.97435864 0.25075255]
 [0.60284258 0.96554517 0.99496186 0.80295574 0.05005817]]
rand_int_arr:
 [[5 3 2 4 1]
 [1 1 4 3 0]
 [2 1 5 3 1]]
identity_matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
empty_arr:
 [[0.5943835  0.27162512 0.35888216 0.60834223 0.92024103]
 [0.45550566 0.85581454 0.74499243 0.97435864 0.25075255]
 [0.60284258 0.96554517 0.99496186 0.80295574 0.05005817]]


## 3. Array Attributes
Inspecting key dimensional and memory properties of a 2D NumPy array.

In [4]:
# Sample 2D array
x = np.random.randint(0, 10, (3, 5))
print("x:\n", x)

# Display structural properties
print(f"Dimensions (ndim): {x.ndim}")
print(f"Shape:            {x.shape}")
print(f"Total elements:   {x.size}")
print(f"Data type:        {x.dtype}")
print(f"Item size (bytes):{x.itemsize}")
print(f"Total size (bytes):{x.nbytes}")

x:
 [[9 4 4 5 1]
 [4 2 3 5 9]
 [0 6 5 7 6]]
Dimensions (ndim): 2
Shape:            (3, 5)
Total elements:   15
Data type:        int32
Item size (bytes):4
Total size (bytes):60


## 4. Array Indexing & Slicing
Accessing and modifying elements across 1D and 2D arrays.

In [5]:
x1 = np.array([1, 2, 3, 4, 5])
print("x1:", x1)

# Element access
first_elem = x1[0]
print("first_elem:", first_elem)
last_elem = x1[-1]
print("last_elem:", last_elem)

# Slicing examples
sub_first_three = x1[0:3]
print("sub_first_three:", sub_first_three)
sub_every_other = x1[::2]
print("sub_every_other:", sub_every_other)
sub_reversed = x1[::-1]
print("sub_reversed:", sub_reversed)

x1: [1 2 3 4 5]
first_elem: 1
last_elem: 5
sub_first_three: [1 2 3]
sub_every_other: [1 3 5]
sub_reversed: [5 4 3 2 1]


In [6]:
# Accessing elements in 2D array [row, column]
corner_val = x[-1, -1]
print("corner_val:", corner_val)

# Modifying elements
x[0, 0] = 10
print("Modified x:\n", x)

# Subsampling a 2x2 subarray
sub_2x2 = x[0:2, 0:2]
print("sub_2x2:\n", sub_2x2)

# Creating an explicit copy to avoid modifying the original array view
y = x[0:2, 0:2].copy()
y[0, 0] = 100
print("y (copy modified):\n", y)

corner_val: 6
Modified x:
 [[10  4  4  5  1]
 [ 4  2  3  5  9]
 [ 0  6  5  7  6]]
sub_2x2:
 [[10  4]
 [ 4  2]]
y (copy modified):
 [[100   4]
 [  4   2]]


## 5. Reshaping & Concatenation
Manipulating array dimensions and merging datasets.

In [7]:
# Reshaping a 1D range into a 3x3 matrix
grid_3x3 = np.arange(0, 9).reshape((3, 3))
print("grid_3x3:\n", grid_3x3)

# Concatenating 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined_1d = np.concatenate([arr1, arr2])
print("combined_1d:", combined_1d)

# Concatenating 2D arrays along axis 1 (columns)
grid = np.arange(1, 7).reshape((2, 3))
combined_2d = np.concatenate([grid, grid], axis=1)
print("combined_2d:\n", combined_2d)

grid_3x3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
combined_1d: [1 2 3 4 5 6]
combined_2d:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## 6. Computation & Universal Functions (Ufuncs)
Vectorized operations for element-wise calculations.

In [8]:
arr_vec = np.arange(4)
print("arr_vec:", arr_vec)

# Basic arithmetic operations
add_res = arr_vec + 5
print("add_res:", add_res)
sub_res = arr_vec - 5
print("sub_res:", sub_res)
mul_res = arr_vec * 2
print("mul_res:", mul_res)
div_res = arr_vec / 2
print("div_res:", div_res)
floor_div_res = arr_vec // 2
print("floor_div_res:", floor_div_res)
pow_res = arr_vec**2
print("pow_res:", pow_res)
mod_res = arr_vec % 2
print("mod_res:", mod_res)

# NumPy ufunc equivalents
np_add = np.add(arr_vec, 2)
print("np_add:", np_add)
np_sub = np.subtract(arr_vec, 2)
print("np_sub:", np_sub)
np_neg = np.negative(arr_vec)
print("np_neg:", np_neg)
np_mul = np.multiply(arr_vec, 5)
print("np_mul:", np_mul)
np_abs = np.absolute(-arr_vec)
print("np_abs:", np_abs)

# Trigonometric ufuncs
theta = np.linspace(0, np.pi, 3)
print("theta:", theta)
sin_vals = np.sin(theta)
print("sin_vals:", sin_vals)
cos_vals = np.cos(theta)
print("cos_vals:", cos_vals)

arr_vec: [0 1 2 3]
add_res: [5 6 7 8]
sub_res: [-5 -4 -3 -2]
mul_res: [0 2 4 6]
div_res: [0.  0.5 1.  1.5]
floor_div_res: [0 0 1 1]
pow_res: [0 1 4 9]
mod_res: [0 1 0 1]
np_add: [2 3 4 5]
np_sub: [-2 -1  0  1]
np_neg: [ 0 -1 -2 -3]
np_mul: [ 0  5 10 15]
np_abs: [0 1 2 3]
theta: [0.         1.57079633 3.14159265]
sin_vals: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos_vals: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


## 7. Aggregations & Missing Data Handling
Computing statistics and managing NaN values safely.

In [9]:
# Vector reduction operations
arr_reduce = np.arange(4)
sum_reduced = np.add.reduce(arr_reduce)
print("sum_reduced:", sum_reduced)
prod_reduced = np.multiply.reduce(arr_reduce)
print("prod_reduced:", prod_reduced)

# Standard aggregations
min_val = np.min(arr_reduce)
print("min_val:", min_val)
max_val = np.max(arr_reduce)
print("max_val:", max_val)
total_sum = np.sum(arr_reduce)
print("total_sum:", total_sum)

# Multidimensional axis aggregations
column_sums = grid.sum(axis=0)
print("column_sums:", column_sums)

# Handling missing data (NaNs) safely
nan_array = np.array([1.0, 2.0, 3.0, 4.0, np.nan])
print("nan_array:", nan_array)

safe_sum = np.nansum(nan_array)
print("safe_sum:", safe_sum)
safe_mean = np.nanmean(nan_array)
print("safe_mean:", safe_mean)
safe_median = np.nanmedian(nan_array)
print("safe_median:", safe_median)

sum_reduced: 6
prod_reduced: 0
min_val: 0
max_val: 3
total_sum: 6
column_sums: [5 7 9]
nan_array: [ 1.  2.  3.  4. nan]
safe_sum: 10.0
safe_mean: 2.5
safe_median: 2.5


## 8. Boolean Masking & Sorting
Filtering values based on conditions and sorting arrays.

In [10]:
data = np.array([1.0, 2.0, 3.0, 4.0, np.nan])
print("data:", data)

# Creating a boolean mask
mask = data > 2
print("mask:", mask)

# Applying the mask
filtered_data = data[data > 2]
print("filtered_data:", filtered_data)

# In-place sorting
unsorted_arr = np.array([50, 2, 25, 18, 7, 10])
unsorted_arr.sort()
print("sorted_arr:", unsorted_arr)

# Checking for NaN values
has_nan = np.isnan(np.nan)
print("has_nan:", has_nan)

data: [ 1.  2.  3.  4. nan]
mask: [False False  True  True False]
filtered_data: [3. 4.]
sorted_arr: [ 2  7 10 18 25 50]
has_nan: True
